# Generated by Django 2.0 on 2017-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translator',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
