# Generated by Django 2.0 on 2017-12-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171215_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
