# Generated by Django 2.0 on 2017-12-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_book_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_edition',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
