# Generated by Django 2.0 on 2018-01-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_link_taoflatpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taoflatpage',
            name='links',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Link'),
        ),
    ]
