# Generated by Django 2.0 on 2018-01-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180130_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taoflatpage',
            name='flatpage_ptr',
        ),
        migrations.RemoveField(
            model_name='taoflatpage',
            name='links',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='TaoFlatPage',
        ),
    ]
