# Generated by Django 2.0 on 2018-01-30 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('blog', '0010_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaoFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('thumbnail', models.ImageField(blank=True, default='img/default.png', null=True, upload_to='img')),
                ('links', models.ManyToManyField(null=True, to='blog.Link')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
